version: "3.8"
services:
  app:
    container_name: pam_erp
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    volumes:
      - ./:/var/www/app
      - vendor_volume:/var/www/app/vendor

    networks:
      - pds
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    container_name: pam_erp_nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - '${FORWARD_NGINX_PORT:-8087}:80'
    volumes:
      - ./:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app
    networks:
      - pds
networks:
  pds:
    driver: bridge
    
volumes:
  vendor_volume:
